apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  namespace: {{ .Values.global.namespace.kafka }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
  annotations:
    strimzi.io/kraft: enabled  # Включаем KRaft-режим
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    metadataVersion: {{ .Values.kafka.metadataVersion }}
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}

---
# Узлы KRaft (Controller/Broker)
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ .Values.kafkaNodePool.name }}
  namespace: {{ .Values.global.namespace.kafka }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  roles:
    - controller                # Роль контроллера
    - broker                   # Роль брокера
  storage:
    type: jbod                  # Используется объединенное хранилище JBOD
    volumes:
      - id: 0                   # Первый диск
        type: {{ .Values.kafkaNodePool.volumes.type }}
        size: {{ .Values.kafkaNodePool.volumes.size }}
        deleteClaim: false       # PV не удалять при удалении пула
        kraftMetadata: shared   # Общие метаданные KRaft