services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./resources:/app/resources
    environment:
      - ENV_VAR_NAME=value
